services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - postgres_db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:4YvQV9HNWfCxylkByXuBArPN411/34aLvmXz9x0jr9A=
      DB_CONNECTION: pgsql
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_DATABASE: BYC_Database
      DB_USERNAME: brzubko
      DB_PASSWORD: MyPass123

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: brzubko
      POSTGRES_PASSWORD: MyPass123
      POSTGRES_DB: BYC_Database
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: zubkobohdan12@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123Pass345
    networks:
      - app_network
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
